name: test

on: 
  push:
    branches:
      - master
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    container: gesztesisz/mosze:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: g++ class.cpp functions.cpp main.cpp storage.cpp
      - name: Permission  Deny  
        run: chmod +x run_test.sh
      - name: I/O test
        run: ./run_test.sh
      - name: Memory leak check
        run: valgrind --error-exitcode=1 ./a.out < input.txt

      - run: doxygen doxconf
      
      - name: Upload doxygen documents 
        uses: s0/git-publish-subdir-action@v2.4.0

        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: DOCS/html
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: Doxygen artifact - HTML
          path: ${{ github.workspace }}/${{env.BUNDLE_PATH}}/DOCS/html

      - uses: actions/upload-artifact@v2
        with:
          name: Doxygen artifact 
          path: ${{ github.workspace }}/${{env.BUNDLE_PATH}}/DOCS/latex